<a href="https://colab.research.google.com/github/fayashi06/Deep-Learning-Classification-/blob/main/startup.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [41]:

!pip install supabase -q

import datetime
from supabase import create_client, Client


SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"

print(" Initializing connection to Solar Synergy Hub backend...")
sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
print(" Connection client successfully established.\n" + "="*50)


current_time_utc = datetime.datetime.now(datetime.timezone.utc)
prediction_window = current_time_utc + datetime.timedelta(hours=1)


iso_timestamp = prediction_window.isoformat()


print("\nStep A: Attempting to sync current weather data logs...")
try:
    weather_payload = {
        "ambient_temperature": 25.3,
        "solar_radiation": 800
    }

    weather_res = sb.table("weather_logs").insert(weather_payload).execute()
    print(" Success! Weather logs updated in data grid.")
    print("   Inserted Data:", weather_res.data)

except Exception as e:
    print("Step A Failed. The table structure or RLS security policies might be blocking this request.")
    print("   Error Details:", e)

print("-" * 50)


print("\n Step B: Attempting to push Machine Learning predictive analytics...")
try:
    predictive_payload = {
        "predicted_temperature": 26.5,
        "predicted_energy_consumption": 1200,
        "prediction_target_time": iso_timestamp
    }

    predict_res = sb.table("predictive_analytics").insert(predictive_payload).execute()
    print("Success! Machine Learning outputs written to database.")
    print("   Inserted Data:", predict_res.data)

except Exception as e:
    print("Step B Failed. Double check that the column headers match your data structure exactly.")
    print("   Error Details:", e)

print("="*50 + "\n Execution complete. Refresh your Lovable cloud viewer panel to inspect changes.")

 Initializing connection to Solar Synergy Hub backend...
 Connection client successfully established.
==================================================

Step A: Attempting to sync current weather data logs...
 Success! Weather logs updated in data grid.
   Inserted Data: [{'id': 'f1a933a1-0b23-4704-b4ac-18c754685288', 'ambient_temperature': 25.3, 'solar_radiation': 800, 'recorded_at': '2026-05-18T21:41:35.129606+00:00', 'created_at': '2026-05-18T21:41:35.129606+00:00'}]
--------------------------------------------------

 Step B: Attempting to push Machine Learning predictive analytics...
Success! Machine Learning outputs written to database.
   Inserted Data: [{'id': 'cd200619-aa63-473d-897b-ceb937c78231', 'predicted_temperature': 26.5, 'predicted_energy_consumption': 1200, 'prediction_target_time': '2026-05-18T22:41:34.08326+00:00', 'created_at': '2026-05-18T21:41:35.409763+00:00', 'weather_status': None, 'estimated_charge_time_hours': None}]
==================================================
 Execution complete. Refresh your Lovable cloud viewer panel to inspect changes.

In [42]:

!pip install supabase requests -q

import datetime
import requests
from supabase import create_client, Client


SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"

# Precise Geographic Coordinates for Baku, Azerbaijan
BAKU_LAT = 40.4093
BAKU_LON = 49.8671

print(" Connecting to Solar Synergy Hub database backend...")
sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
print(" Connection client successfully established.")

# ==============================================================================
# 3. FETCH LIVE BAKU WEATHER DATA
# ==============================================================================
print("\nFetching real-time weather metrics for Baku from Open-Meteo...")

# Pulling real-time temperature and shortwave solar radiation flux values
weather_url = f"https://api.open-meteo.com/v1/forecast?latitude={BAKU_LAT}&longitude={BAKU_LON}&current=temperature_2m,shortwave_radiation&timezone=auto"

try:
    weather_response = requests.get(weather_url).json()
    current_metrics = weather_response["current"]

    baku_temp = float(current_metrics["temperature_2m"])         # Ambient Temp (°C)
    baku_solar = float(current_metrics["shortwave_radiation"])    # Solar Flux (W/m²)

    print(f"Live Baku Data Found -> Temperature: {baku_temp}°C | Solar Radiation: {baku_solar} W/m²")

except Exception as weather_err:
    print("API network issue. Dropping in standard baseline fallbacks for Baku instead.")
    baku_temp = 25.3
    baku_solar = 800.0

# ==============================================================================
# 4. TIMESTAMPS AND MACHINE LEARNING PREDICTIVE TARGETS
# ==============================================================================
# Generate a clean, modern timezone-aware UTC timestamp targeting the prediction hour
current_time_utc = datetime.datetime.now(datetime.timezone.utc)
prediction_window = current_time_utc + datetime.timedelta(hours=1)
iso_timestamp = prediction_window.isoformat()

# Simulated Machine Learning Predictor Logic (Replace these with your exact model arrays/variables later)
ml_predicted_temp = round(baku_temp + 1.2, 2)
ml_predicted_consumption = round(480.5 + (baku_temp * 4.2), 2)

# ==============================================================================
# 5. EXECUTE REAL-TIME DATABASE STREAMING
# ==============================================================================

# --- TASK A: Stream Current Metrics into weather_logs ---
print("\n Step A: Syncing live Baku weather data...")
try:
    weather_payload = {
        "ambient_temperature": baku_temp,
        "solar_radiation": baku_solar
    }
    weather_res = sb.table("weather_logs").insert(weather_payload).execute()
    print(" Success! Current weather table updated:", weather_res.data)
except Exception as e:
    print("Step A Failed. Check if the table columns exactly match 'ambient_temperature' and 'solar_radiation':")
    print(e)

print("-" * 50)

# --- TASK B: Stream Target Forecasts into predictive_analytics ---
print("\n Step B: Uploading Predictive Machine Learning Analytics...")
try:
    predictive_payload = {
        "predicted_temperature": ml_predicted_temp,
        "predicted_energy_consumption": ml_predicted_consumption,
        "prediction_target_time": iso_timestamp
    }
    predict_res = sb.table("predictive_analytics").insert(predictive_payload).execute()
    print(" Success! Predictive analytics rows generated:", predict_res.data)
except Exception as e:
    print(" Step B Failed. Check schema mapping definitions:")
    print(e)

print("="*50 + "\n Execution complete. Refresh your Lovable cloud data tabs to inspect changes.")

 Connecting to Solar Synergy Hub database backend...
 Connection client successfully established.

Fetching real-time weather metrics for Baku from Open-Meteo...
Live Baku Data Found -> Temperature: 16.9°C | Solar Radiation: 0.0 W/m²

 Step A: Syncing live Baku weather data...
 Success! Current weather table updated: [{'id': '31e90f4a-8f38-49c5-9ea7-dd2edef973a9', 'ambient_temperature': 16.9, 'solar_radiation': 0.0, 'recorded_at': '2026-05-18T21:41:47.419331+00:00', 'created_at': '2026-05-18T21:41:47.419331+00:00'}]
--------------------------------------------------

 Step B: Uploading Predictive Machine Learning Analytics...
 Success! Predictive analytics rows generated: [{'id': '1961fcdb-a7df-4bec-bc4b-6bfff785a615', 'predicted_temperature': 18.1, 'predicted_energy_consumption': 551.48, 'prediction_target_time': '2026-05-18T22:41:46.639967+00:00', 'created_at': '2026-05-18T21:41:47.617069+00:00', 'weather_status': None, 'estimated_charge_time_hours': None}]
==================================================
 Execution complete. Refresh your Lovable cloud data tabs to inspect changes.

In [43]:
# ==============================================================================
# 1. INSTALL AND IMPORT DEPENDENCIES
# ==============================================================================
!pip install supabase requests pandas numpy -q

import datetime
import random
import numpy as np
import pandas as pd
from supabase import create_client, Client

# ==============================================================================
# 2. DATABASE CONFIGURATION
# ==============================================================================
SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"

sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
print(" Connected to Solar Synergy Hub for bulk ingestion...")

# ==============================================================================
# 3. GENERATE 30 DAYS OF HOURLY TRAINING DATA (BAKU CLIMATE SYNTHESIS)
# ==============================================================================
print(" Generating 720 hours of climate and load data for ML training...")

# Create hourly timestamps for the past 30 days
base_time = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=30)
timestamps = [base_time + datetime.timedelta(hours=i) for i in range(720)]

weather_logs_batch = []
predictive_analytics_batch = []

for ts in timestamps:
    hour = ts.hour

    # Base diurnal temperature wave for Baku (peaks around 15:00, coolest at 05:00)
    base_temp = 22.0 + 6.0 * np.sin(2 * np.pi * (hour - 9) / 24)
    # Add a bit of stochastic weather noise
    ambient_temp = round(base_temp + random.uniform(-2.0, 2.0), 2)

    # Solar radiation model (clear day bell-curve between 06:00 and 19:00)
    if 6 <= hour <= 19:
        solar_radiation = round(900 * np.sin(np.pi * (hour - 6) / 13) + random.uniform(-50, 50), 2)
        solar_radiation = max(0.0, solar_radiation)
    else:
        solar_radiation = 0.0

    # Energy consumption prediction target (higher during grid peak hours and high temps due to cooling load)
    base_load = 350.0 + (ambient_temp * 4.5)
    if 9 <= hour <= 18:  # Commercial peak operational hours
        base_load += 180.0
    predicted_energy = round(base_load + random.uniform(-30, 30), 2)

    # Format strings for DB entry
    iso_string = ts.isoformat()

    # Append to respective batch payloads
    weather_logs_batch.append({
        "ambient_temperature": ambient_temp,
        "solar_radiation": solar_radiation,
        "created_at": iso_string
    })

    predictive_analytics_batch.append({
        "predicted_temperature": round(ambient_temp + random.uniform(-0.5, 0.5), 2),
        "predicted_energy_consumption": predicted_energy,
        "prediction_target_time": iso_string
    })

# ==============================================================================
# 4. BULK UPLOAD TO SUPABASE (BATCHED IN PIECES OF 200 TO PREVENT TIMEOUTS)
# ==============================================================================
BATCH_SIZE = 200

print(f"\n Streaming {len(weather_logs_batch)} rows into 'weather_logs'...")
try:
    for i in range(0, len(weather_logs_batch), BATCH_SIZE):
        chunk = weather_logs_batch[i:i+BATCH_SIZE]
        sb.table("weather_logs").insert(chunk).execute()
    print(" 'weather_logs' table holds extended baseline data!")
except Exception as e:
    print(" Failed bulk upload to weather_logs:", e)

print(f"\n Streaming {len(predictive_analytics_batch)} rows into 'predictive_analytics'...")
try:
    for i in range(0, len(predictive_analytics_batch), BATCH_SIZE):
        chunk = predictive_analytics_batch[i:i+BATCH_SIZE]
        sb.table("predictive_analytics").insert(chunk).execute()
    print(" 'predictive_analytics' table holds full target dataset feature arrays!")
except Exception as e:
    print("Failed bulk upload to predictive_analytics:", e)

print("="*60 + "\n Complete database hydration successful! You now have a solid dataset to feed your ML models.")

 Connected to Solar Synergy Hub for bulk ingestion...
 Generating 720 hours of climate and load data for ML training...

 Streaming 720 rows into 'weather_logs'...
 'weather_logs' table holds extended baseline data!

 Streaming 720 rows into 'predictive_analytics'...
 'predictive_analytics' table holds full target dataset feature arrays!
============================================================
 Complete database hydration successful! You now have a solid dataset to feed your ML models.

In [44]:
df = pd.DataFrame(sb.table("predictive_analytics").select("*").execute().data)

In [45]:
df

,id,predicted_temperature,predicted_energy_consumption,prediction_target_time,created_at,weather_status,estimated_charge_time_hours
0,4d914bae-ea0b-442e-bd18-765e61be8b3c,26.50,1200.00,2026-05-17T20:25:21.170044+00:00,2026-05-17T19:25:21.928847+00:00,None,NaN
1,8b927c29-1642-47f6-92ab-de0d16137a5f,26.50,1200.00,2026-05-17T20:26:11.432122+00:00,2026-05-17T19:26:11.977467+00:00,None,NaN
2,de2124e4-0781-459e-91cb-4874189c7b85,26.50,1200.00,2026-05-17T20:26:25.643235+00:00,2026-05-17T19:26:25.935479+00:00,None,NaN
3,217d6818-5da4-4c58-b51a-125cd29bf8b8,17.10,547.28,2026-05-17T20:31:01.312707+00:00,2026-05-17T19:31:02.108544+00:00,None,NaN
4,413dc466-2e24-4587-a61a-33833d01b853,17.10,547.28,2026-05-17T20:31:19.229275+00:00,2026-05-17T19:31:19.728228+00:00,None,NaN
...,...,...,...,...,...,...,...
995,054b550e-0750-4cf8-be29-ef5c0998ce04,17.08,400.56,2026-04-27T06:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
996,da15cdaf-6e77-4a43-8fff-de005a765383,18.55,401.94,2026-04-27T07:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
997,d3e27ea3-f97d-4114-9935-98252670d3f7,19.31,411.61,2026-04-27T08:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
998,7d77c354-c0be-49ba-8b94-709255b05d19,20.33,643.41,2026-04-27T09:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
999,8a5ec6f9-fa69-4d07-aa2a-42cf530cc605,24.13,636.87,2026-04-27T10:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN

In [46]:
# ==============================================================================
# 1. INSTALL AND IMPORT DEPENDENCIES
# ==============================================================================
!pip install supabase requests -q

import datetime
import requests
from supabase import create_client, Client

# ==============================================================================
# 2. CONFIGURATION & CREDENTIALS
# ==============================================================================
SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"

sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Baku coordinates
BAKU_LAT = 40.4093
BAKU_LON = 49.8671

print(" Fetching tomorrow's hourly solar forecast for Baku...")

# ==============================================================================
# 3. FETCH 24-HOUR HOURLY SOLAR FORECAST
# ==============================================================================
forecast_url = f"https://api.open-meteo.com/v1/forecast?latitude={BAKU_LAT}&longitude={BAKU_LON}&hourly=temperature_2m,shortwave_radiation,weathercode&timezone=auto&forecast_days=1"

try:
    response = requests.get(forecast_url).json()
    hourly_data = response["hourly"]

    times = hourly_data["time"]                      # List of ISO timestamps
    temperatures = hourly_data["temperature_2m"]     # List of hourly temps
    solar_fluxes = hourly_data["shortwave_radiation"] # Solar radiation (W/m²)

    print(f"☀️ Successfully parsed {len(times)} hourly data points for Baku.")
except Exception as e:
    print("❌ Failed to pull forecast data:", e)
    times, temperatures, solar_fluxes = [], [], []

# ==============================================================================
# 4. PROCESS ML PREDICTIONS AND SMART CHARGING METRICS
# ==============================================================================
predictive_analytics_batch = []

# Baseline constants for a typical EV charging session at your smart carport
BATTERY_CAPACITY_NEEDED = 40.0  # assume average user needs 40 kWh to top off
MAX_CHARGER_POWER_KW = 11.0     # standard Level 2 AC charger max speed
CARPORT_SOLAR_CAPACITY_KW = 15.0 # peak size of the canopy solar array

for i in range(len(times)):
    target_time = times[i]
    temp = temperatures[i]
    solar = solar_fluxes[i]

    # ML Prediction modeling simulation
    # In your final model, replace these equations with your trained SVM/Random Forest models
    predicted_consumption = round(300.0 + (temp * 5.2) + (solar * 0.15), 2)

    # --- EV CHARGING LOGIC BASED ON WEATHER ---
    # Calculate real-time available solar charging power factor
    # Standard solar efficiency reduction happens if it's cloudy or dark
    available_solar_generation = (solar / 1000.0) * CARPORT_SOLAR_CAPACITY_KW

    # Active charging speed depends heavily on solar availability
    # If solar is low, system dynamically switches to base grid power (slower eco-mode or premium grid tier)
    actual_charging_power = min(MAX_CHARGER_POWER_KW, max(3.7, available_solar_generation))

    # Calculate Estimated Time to Charge (ETC) in hours
    etc_hours = round(BATTERY_CAPACITY_NEEDED / actual_charging_power, 1)

    # Format description for the user UI based on solar availability
    if solar > 500:
        weather_status = " Sunny - Peak Solar Speed"
    elif solar > 150:
        weather_status = " Partly Cloudy - Balanced Charging"
    else:
        weather_status = " Low Solar / Night - Grid Backup Mode"

    predictive_analytics_batch.append({
        "predicted_temperature": float(temp),
        "predicted_energy_consumption": float(predicted_consumption),
        "prediction_target_time": target_time,
        # We store these extra custom attributes so Lovable can display them beautifully to the user
        "weather_status": weather_status,
        "estimated_charge_time_hours": float(etc_hours)
    })

# ==============================================================================
# 5. STREAM FORECAST ARRAY INTO LOVABLE BACKEND
# ==============================================================================
print(f"\n📡 Uploading forecast matrix to 'predictive_analytics'...")
try:
    # Clear out older stale forecasts first if desired, or simply insert the new timeline
    sb.table("predictive_analytics").insert(predictive_analytics_batch).execute()
    print("Success! 24-Hour Solar Ingestion Matrix fully synced.")
except Exception as e:
    print(" Failed bulk upload:", e)

 Fetching tomorrow's hourly solar forecast for Baku...
☀️ Successfully parsed 24 hourly data points for Baku.

📡 Uploading forecast matrix to 'predictive_analytics'...
Success! 24-Hour Solar Ingestion Matrix fully synced.

In [47]:
# ==============================================================================
# 1. INSTALL AND IMPORT DEPENDENCIES
# ==============================================================================
!pip install supabase requests -q

import datetime
import requests
from supabase import create_client, Client

# ==============================================================================
# 2. CONFIGURATION & CREDENTIALS
# ==============================================================================
SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"

sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Baku coordinates
BAKU_LAT = 40.4093
BAKU_LON = 49.8671

print(" Fetching hourly solar forecast for Baku...")

# ==============================================================================
# 3. FETCH 24-HOUR HOURLY SOLAR FORECAST
# ==============================================================================
forecast_url = f"https://api.open-meteo.com/v1/forecast?latitude={BAKU_LAT}&longitude={BAKU_LON}&hourly=temperature_2m,shortwave_radiation&timezone=auto&forecast_days=1"

try:
    response = requests.get(forecast_url).json()
    hourly_data = response["hourly"]

    times = hourly_data["time"]
    temperatures = hourly_data["temperature_2m"]
    solar_fluxes = hourly_data["shortwave_radiation"]

    print(f" Successfully parsed {len(times)} hourly data points for Baku.")
except Exception as e:
    print(" Failed to pull forecast data:", e)
    times, temperatures, solar_fluxes = [], [], []

# ==============================================================================
# 4. PROCESS CHOSEN METRICS & RE-ALIGNED DATABASE STRUCTURE
# ==============================================================================
predictive_analytics_batch = []

# Engineering baselines for your smart carport charger setup
BATTERY_CAPACITY_NEEDED = 40.0  # target kWh average user needs to fully charge
MAX_CHARGER_POWER_KW = 11.0     # Level 2 charger upper threshold
CARPORT_SOLAR_CAPACITY_KW = 15.0 # Total canopy solar array rating

for i in range(len(times)):
    target_time = times[i]
    temp = temperatures[i]
    solar = solar_fluxes[i]

    # Machine Learning Simulation equations (Replace with your direct model outputs later)
    predicted_consumption = round(300.0 + (temp * 5.2) + (solar * 0.15), 2)

    # Calculate solar-dependent charging capacity
    available_solar_generation = (solar / 1000.0) * CARPORT_SOLAR_CAPACITY_KW
    actual_charging_power = min(MAX_CHARGER_POWER_KW, max(3.7, available_solar_generation))

    # Compute the Estimated Time to Charge (ETC) in hours
    etc_hours = round(BATTERY_CAPACITY_NEEDED / actual_charging_power, 1)

    # Classify weather text based on solar flux intensity
    if solar > 500:
        weather_status = "Sunny - Peak Solar Speed "
    elif solar > 150:
        weather_status = "Partly Cloudy - Balanced Charging "
    else:
        weather_status = "Low Solar / Night - Grid Backup Mode "

    # Match the updated database schema exactly
    predictive_analytics_batch.append({
        "predicted_temperature": float(temp),
        "predicted_energy_consumption": float(predicted_consumption),
        "prediction_target_time": target_time,
        "weather_status": weather_status,                       # New column matching table
        "estimated_charge_time_hours": float(etc_hours)          # New column matching table
    })

# ==============================================================================
# 5. STREAM FORECAST MATRIX INTO BACKEND
# ==============================================================================
print(f"\n Uploading updated forecast matrix to 'predictive_analytics'...")
try:
    sb.table("predictive_analytics").insert(predictive_analytics_batch).execute()
    print(" Success! Data with extended charging predictions successfully synced with your backend.")
except Exception as e:
    print(" Upload failed. Make sure Lovable has finished adding the columns:")
    print(e)

 Fetching hourly solar forecast for Baku...
 Successfully parsed 24 hourly data points for Baku.

 Uploading updated forecast matrix to 'predictive_analytics'...
 Success! Data with extended charging predictions successfully synced with your backend.

In [48]:
# ==============================================================================
# 1. INSTALL AND IMPORT CORE LIBRARIES
# ==============================================================================
!pip install supabase requests pandas numpy scikit-learn -q

import datetime
import random
import requests
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from supabase import create_client, Client

# Database Credentials
SUPABASE_URL = "https://ykulodkmmswrmkyjlvpi.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdWxvZGttbXN3cm1reWpsdnBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg3NTEwNDEsImV4cCI6MjA5NDMyNzA0MX0.zY6jRfHQ2fSjNKKUlliBQQNLn6l0DfgkiVuPecK-SPQ"
sb: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

# Baku Coordinates & Smart Carport Technical Assets
BAKU_LAT, BAKU_LON = 40.4093, 49.8671
BATTERY_CAPACITY_NEEDED = 40.0   # Standard mid-size EV top-off (kWh)
CARPORT_SOLAR_CAPACITY_KW = 15.0 # Peak solar canopy rating
MAX_CHARGER_POWER_KW = 11.0      # Three-phase Level 2 AC charger max speed

# ==============================================================================
# REAL AZERBAIJANI TARIFF MODEL (Tarif Şurası Commercial Base)
# ==============================================================================
GRID_RATE_AZN = 0.10   # Official regulated commercial rate for EV charging in Azerbaijan
SOLAR_RATE_AZN = 0.07  # Your startup's discounted green incentive rate to attract users

# ==============================================================================
# 2. GENERATE HISTORICAL TRAINING DATA (SYNTHETIC BAKU GRID LOAD)
# ==============================================================================
print(" Step 1: Synthesizing historical training dataset (30 days for Baku)...")
base_time = datetime.datetime.now(datetime.timezone.utc) - datetime.timedelta(days=30)
training_data = []

for i in range(720):
    ts = base_time + datetime.timedelta(hours=i)
    hour = ts.hour

    # Baku temperature cycles + solar curve simulation
    temp = 22.0 + 6.0 * np.sin(2 * np.pi * (hour - 9) / 24) + random.uniform(-2, 2)
    solar = max(0.0, 900 * np.sin(np.pi * (hour - 6) / 13) + random.uniform(-50, 50)) if 6 <= hour <= 19 else 0.0

    # Mathematical baseline load relationship for the ML model to learn
    base_load = 300.0 + (temp * 5.2) + (solar * 0.15)
    if 9 <= hour <= 18: base_load += 150.0  # Commercial peak hours
    actual_load = base_load + random.uniform(-20, 20)

    training_data.append({"ambient_temperature": temp, "solar_radiation": solar, "hour": hour, "actual_consumption": actual_load})

df_train = pd.DataFrame(training_data)

# ==============================================================================
# 3. TRAIN THE RANDOM FOREST REGRESSOR ENGINE
# ==============================================================================
print(" Step 2: Training the Machine Learning Predictive Engine...")
X = df_train[['ambient_temperature', 'solar_radiation', 'hour']]
y = df_train['actual_consumption']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
ml_model = RandomForestRegressor(n_estimators=100, random_state=42)
ml_model.fit(X_train, y_train)
print("    Training complete.")

# ==============================================================================
# 4. FETCH REAL 24-HOUR FORECAST FOR BAKU & INFER FINANCIALS
# ==============================================================================
print("\n Step 3: Pulling current meteorological forecast arrays for Baku...")
forecast_url = f"https://api.open-meteo.com/v1/forecast?latitude={BAKU_LAT}&longitude={BAKU_LON}&hourly=temperature_2m,shortwave_radiation&timezone=auto&forecast_days=1"
hourly_data = requests.get(forecast_url).json()["hourly"]

times = hourly_data["time"]
temperatures = hourly_data["temperature_2m"]
solar_fluxes = hourly_data["shortwave_radiation"]

predictive_analytics_batch = []

print(" Step 4: Computing dynamic session costs using real Azerbaijani grid tariffs...")
for i in range(len(times)):
    target_time = times[i]
    temp = temperatures[i]
    solar = solar_fluxes[i]
    parsed_hour = pd.to_datetime(target_time).hour

    # 1. Run Machine Learning Inference for system load
    ml_input = [[float(temp), float(solar), int(parsed_hour)]]
    predicted_consumption = float(ml_model.predict(ml_input)[0])

    # 2. Physics-based Charging Speed Calculations
    available_solar_kw = (solar / 1000.0) * CARPORT_SOLAR_CAPACITY_KW
    actual_charging_kw = min(MAX_CHARGER_POWER_KW, max(3.7, available_solar_kw))
    etc_hours = round(BATTERY_CAPACITY_NEEDED / actual_charging_kw, 1)

    # 3. Real-Time Dynamic Cost Pricing Formulation (AZN)
    solar_ratio = min(1.0, available_solar_kw / actual_charging_kw) if actual_charging_kw > 0 else 0
    blended_rate_per_kwh = (solar_ratio * SOLAR_RATE_AZN) + ((1 - solar_ratio) * GRID_RATE_AZN)
    total_session_cost_azn = round(BATTERY_CAPACITY_NEEDED * blended_rate_per_kwh, 2)

    # Encoding pricing metadata string directly to circumvent Lovable's chat building tier limitations
    if solar > 500:
        weather_status = f"Sunny (Time: {etc_hours}h | Cost: {total_session_cost_azn:.2f} AZN)"
    elif solar > 150:
        weather_status = f"Cloudy  (Time: {etc_hours}h | Cost: {total_session_cost_azn:.2f} AZN)"
    else:
        weather_status = f"Night  (Time: {etc_hours}h | Cost: {total_session_cost_azn:.2f} AZN)"

    predictive_analytics_batch.append({
        "predicted_temperature": float(temp),
        "predicted_energy_consumption": round(predicted_consumption, 2),
        "prediction_target_time": target_time,
        "weather_status": weather_status,
        "estimated_charge_time_hours": float(etc_hours)
    })

# ==============================================================================
# 5. DATA INGESTION UPLOAD
# ==============================================================================
print("\n Step 5: Syncing localized analytical matrix array with website database...")
try:
    sb.table("predictive_analytics").insert(predictive_analytics_batch).execute()
    print(" SUCCESS! Your live database grid is updated with true Azerbaijani operational costs.")
except Exception as e:
    print(" Upload failed:", e)

 Step 1: Synthesizing historical training dataset (30 days for Baku)...
 Step 2: Training the Machine Learning Predictive Engine...
    Training complete.

 Step 3: Pulling current meteorological forecast arrays for Baku...
 Step 4: Computing dynamic session costs using real Azerbaijani grid tariffs...

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

 Step 5: Syncing localized analytical matrix array with website database...
 SUCCESS! Your live database grid is updated with true Azerbaijani operational costs.

In [49]:
# === Push forecasts to SolarPark site ===
!pip install -q supabase

from supabase import create_client
from datetime import datetime, timedelta, timezone

SUPABASE_URL = "https://pcofeynkqnpnjygbgkha.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2ZleW5rcW5wbmp5Z2Jna2hhIiwicm9sZSI6ImF"

In [50]:
# === Push forecasts to SolarPark site ===
!pip install -q supabase

from supabase import create_client
from datetime import datetime, timedelta, timezone

SUPABASE_URL = "https://pcofeynkqnpnjygbgkha.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2ZleW5rcW5wbmp5Z2Jna2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMjU2NDksImV4cCI6MjA5NDcwMTY0OX0.Ptz2iOdSnIaprxV320T8rguA8Q9nkvlqJB01ND65EVY"

sb = create_client(SUPABASE_URL, SUPABASE_KEY)

# Optional: clear old forecast window so the timeline only shows the new run
sb.table("predictive_analytics").delete().gte(
    "prediction_target_time",
    (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
).execute()

# ---- Build 24 hourly rows from your model ----
# Extracting model outputs from the previously generated predictive_analytics_batch
temps = [item["predicted_temperature"] for item in predictive_analytics_batch]
energy = [item["predicted_energy_consumption"] for item in predictive_analytics_batch]
charge_hours = [item["estimated_charge_time_hours"] for item in predictive_analytics_batch]
# Extract only the weather condition part, e.g., "Sunny" from "Sunny (Time: ...)"
condition = [item["weather_status"].split(" (")[0] for item in predictive_analytics_batch]

EMOJI = {"Sunny":"☀️","Cloudy":"☁️","Rainy":"🌧️","Partly Cloudy":"⛅","Snowy":"❄️"}

now = datetime.now(timezone.utc).replace(minute=0, second=0, microsecond=0)
rows = []
for i in range(24):
    t        = float(temps[i])
    e        = float(energy[i])
    hrs      = float(charge_hours[i])
    cond     = str(condition[i])
    cost     = round(e * (0.07 if cond == "Sunny" else 0.10), 2)  # AZN
    status   = f"{cond} {EMOJI.get(cond,'•')} (Time: {hrs:.1f}h | Cost: {cost:.2f} AZN)"
    rows.append({
        "prediction_target_time": (now + timedelta(hours=i+1)).isoformat(),
        "predicted_temperature": t,
        "predicted_energy_consumption": e,
        "estimated_charge_time_hours": hrs,
        "weather_status": status,
    })

res = sb.table("predictive_analytics").insert(rows).execute()
print(f" Pushed {len(res.data)} forecast rows to SolarPark.")

 Pushed 24 forecast rows to SolarPark.

In [51]:
df

,id,predicted_temperature,predicted_energy_consumption,prediction_target_time,created_at,weather_status,estimated_charge_time_hours
0,4d914bae-ea0b-442e-bd18-765e61be8b3c,26.50,1200.00,2026-05-17T20:25:21.170044+00:00,2026-05-17T19:25:21.928847+00:00,None,NaN
1,8b927c29-1642-47f6-92ab-de0d16137a5f,26.50,1200.00,2026-05-17T20:26:11.432122+00:00,2026-05-17T19:26:11.977467+00:00,None,NaN
2,de2124e4-0781-459e-91cb-4874189c7b85,26.50,1200.00,2026-05-17T20:26:25.643235+00:00,2026-05-17T19:26:25.935479+00:00,None,NaN
3,217d6818-5da4-4c58-b51a-125cd29bf8b8,17.10,547.28,2026-05-17T20:31:01.312707+00:00,2026-05-17T19:31:02.108544+00:00,None,NaN
4,413dc466-2e24-4587-a61a-33833d01b853,17.10,547.28,2026-05-17T20:31:19.229275+00:00,2026-05-17T19:31:19.728228+00:00,None,NaN
...,...,...,...,...,...,...,...
995,054b550e-0750-4cf8-be29-ef5c0998ce04,17.08,400.56,2026-04-27T06:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
996,da15cdaf-6e77-4a43-8fff-de005a765383,18.55,401.94,2026-04-27T07:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
997,d3e27ea3-f97d-4114-9935-98252670d3f7,19.31,411.61,2026-04-27T08:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
998,7d77c354-c0be-49ba-8b94-709255b05d19,20.33,643.41,2026-04-27T09:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
999,8a5ec6f9-fa69-4d07-aa2a-42cf530cc605,24.13,636.87,2026-04-27T10:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN

In [52]:
!pip install -q supabase

from supabase import create_client
from datetime import datetime, timedelta, timezone
import math

SUPABASE_URL = "https://pcofeynkqnpnjygbgkha.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2ZleW5rcW5wbmp5Z2Jna2hhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxMjU2NDksImV4cCI6MjA5NDcwMTY0OX0.Ptz2iOdSnIaprxV320T8rguA8Q9nkvlqJB01ND65EVY"

sb = create_client(SUPABASE_URL, SUPABASE_KEY)

sb.table("predictive_analytics").delete().gte(
    "prediction_target_time",
    (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
).execute()

class DiurnalTemperaturePredictor:
    def __init__(self, daily_average_temp=22.0, max_fluctuation=6.0):
        self.avg_temp = daily_average_temp
        self.fluctuation = max_fluctuation

    def predict(self, target_datetime):
        hour = target_datetime.hour
        temp = self.avg_temp + self.fluctuation * math.sin((hour - 9) * (math.pi / 12))
        return round(temp, 2)

temp_predictor = DiurnalTemperaturePredictor(daily_average_temp=25.0, max_fluctuation=5.0)

energy = [item["predicted_energy_consumption"] for item in predictive_analytics_batch]
charge_hours = [item["estimated_charge_time_hours"] for item in predictive_analytics_batch]
condition = [item["weather_status"].split(" (")[0] for item in predictive_analytics_batch]

now = datetime.now(timezone.utc).replace(minute=0, second=0, microsecond=0)
rows = []

for i in range(24):
    target_time = now + timedelta(hours=i+1)

    t = temp_predictor.predict(target_time)

    e        = float(energy[i])
    hrs      = float(charge_hours[i])
    cond     = str(condition[i])
    cost     = round(e * (0.07 if cond == "Sunny" else 0.10), 2)
    status   = f"{cond} (Time: {hrs:.1f}h | Cost: {cost:.2f} AZN)"

    rows.append({
        "prediction_target_time": target_time.isoformat(),
        "predicted_temperature": t,
        "predicted_energy_consumption": e,
        "estimated_charge_time_hours": hrs,
        "weather_status": status,
    })

res = sb.table("predictive_analytics").insert(rows).execute()
print(f"Pushed {len(res.data)} forecast rows to SolarPark.")

Pushed 24 forecast rows to SolarPark.

In [53]:
df

,id,predicted_temperature,predicted_energy_consumption,prediction_target_time,created_at,weather_status,estimated_charge_time_hours
0,4d914bae-ea0b-442e-bd18-765e61be8b3c,26.50,1200.00,2026-05-17T20:25:21.170044+00:00,2026-05-17T19:25:21.928847+00:00,None,NaN
1,8b927c29-1642-47f6-92ab-de0d16137a5f,26.50,1200.00,2026-05-17T20:26:11.432122+00:00,2026-05-17T19:26:11.977467+00:00,None,NaN
2,de2124e4-0781-459e-91cb-4874189c7b85,26.50,1200.00,2026-05-17T20:26:25.643235+00:00,2026-05-17T19:26:25.935479+00:00,None,NaN
3,217d6818-5da4-4c58-b51a-125cd29bf8b8,17.10,547.28,2026-05-17T20:31:01.312707+00:00,2026-05-17T19:31:02.108544+00:00,None,NaN
4,413dc466-2e24-4587-a61a-33833d01b853,17.10,547.28,2026-05-17T20:31:19.229275+00:00,2026-05-17T19:31:19.728228+00:00,None,NaN
...,...,...,...,...,...,...,...
995,054b550e-0750-4cf8-be29-ef5c0998ce04,17.08,400.56,2026-04-27T06:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
996,da15cdaf-6e77-4a43-8fff-de005a765383,18.55,401.94,2026-04-27T07:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
997,d3e27ea3-f97d-4114-9935-98252670d3f7,19.31,411.61,2026-04-27T08:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
998,7d77c354-c0be-49ba-8b94-709255b05d19,20.33,643.41,2026-04-27T09:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN
999,8a5ec6f9-fa69-4d07-aa2a-42cf530cc605,24.13,636.87,2026-04-27T10:09:31.183107+00:00,2026-05-18T16:09:31.808389+00:00,None,NaN

In [56]:
from datetime import datetime, timedelta, timezone

base_time = datetime.now(timezone.utc).replace(minute=0, second=0, microsecond=0)

rows = []
for i in range(24):
    target_time = base_time + timedelta(hours=i)
    rows.append({
        "prediction_target_time": target_time.isoformat(),
        "predicted_temperature": float(temps[i]),
        "predicted_energy_consumption": float(energy[i]),
        "estimated_charge_time_hours": float(charge_hours[i]),
        "weather_status": condition[i],  # e.g. "Sunny ☀️ (Time: 3.6h | Cost: 2.80 AZN)"
    })